FROM python:3.10

WORKDIR /app

COPY . /app

RUN python -m pip install --upgrade pip

RUN pip install -r frontend/requirements.txt

EXPOSE 8003

CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port", "8003"]